language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
  - jruby-18mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2.1
  - rbx-2.2
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: 1.8.7
  fast_finish: true
install: bundle install --jobs=1 --retry=3